### ISSUE TITLE
404 Not found

### ISSUE THREAD

**Issue by Jan-David-Black** [gdsfactory/kweb#15]
Hey guys,
when visiting /gds/wg I end up with a json document saying `404 not found`. Any idea why that could be? I checked and the `gds` and template files seem to be in the right place and should be found.
Regards JD

**Comment by sebastian-goeldi** [comment]
Hey,

Yes, it's because we had to use a different url scheme to make it compatible with sending the file path to kweb instead of fixed cells available, the docs never got updated because I wanted to automate & integrate with jupyter.

I'll update the README it a bit later today, sorry about that.

**Comment by Jan-David-Black** [comment]
Ah ok no worries :) Feel free to close the issue when the docs are up to date then.

**Comment by Jan-David-Black** [comment]
Fixed by version 0.1.1
