### ISSUE TITLE
move gds

### ISSUE THREAD

**Issue by SouthChinaHuihuisauce** [gdsfactory/kweb#25]
![move](https://github.com/gdsfactory/kweb/assets/95074184/d38fc1c2-88b6-49c5-b973-fbecf7041c9e)
I tried to move the GDS graphics, but it didn't work. Do I need to modify where to take effect?

**Comment by sebastian-goeldi** [comment]
1) You need to make sure it's opened in editable mode (which I think kweb does, otherwise the buttons won't show up).

2) let's keep this open until klayout fixes the bugs and then pin a minimum version https://github.com/KLayout/klayout/issues/1404

**Comment by SouthChinaHuihuisauce** [comment]
> 1. You need to make sure it's opened in editable mode (which I think kweb does, otherwise the buttons won't show up).
> 2. let's keep this open until klayout fixes the bugs and then pin a minimum version [Editing API under Editor KLayout/klayout#1404](https://github.com/KLayout/klayout/issues/1404)

Okay, thank you very much for your reply

**Comment by sebastian-goeldi** [comment]
Should work with the new kweb 1.0
