### ISSUE TITLE
kweb issues

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/kweb#26]
kweb demo has some issues with the hierarchy not showing correctly

![image](https://github.com/gdsfactory/kweb/assets/4514346/5cae4bd9-0111-436f-ad5c-b5b7cb8e8736)

![image](https://github.com/gdsfactory/kweb/assets/4514346/9da52bbb-6cbc-411b-802b-00be2d2e4b4b)

@Jan-David-Black 
@sebastian-goeldi

**Comment by sebastian-goeldi** [comment]
I guess this is now pretty obsolete ;)
