### ISSUE TITLE
TODOs

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/kweb#3]
- [x] load layer properties file #11 
- [ ] add tests

Maybe:

- [ ] add 2.5D visualization

@sebastian-goeldi 
@proppy
@tvt173
@skandanc
@klayoutmatthias
@mbalestrini

**Comment by sebastian-goeldi** [comment]
layer properties file can just be loaded with https://www.klayout.de/doc-qt5/code/class_LayoutView.html#method128 and added to the server here https://github.com/gdsfactory/kweb/blob/main/src/kweb/server.py#L69 . I am terrible with web design, so I'll leave the frontend for selecting something to other people ;)

**Comment by sebastian-goeldi** [comment]
I don't think 2.5d is realistic for kweb. I don't even think this is exposed as it uses its own window in klayout. We can do it at some point if it is exposed, but for now I think this is a pretty big stretch of scope
