### ISSUE TITLE
Can we not load the whole GDS in memory when rendering?

### ISSUE THREAD

**Issue by Ealameda31** [gdsfactory/kweb#39]
Can be GB - not good on a server where you are supporting heaps of users.

**Comment by sebastian-goeldi** [comment]
Limitation of klayout. ~~Divide~~Distribute and conquer ;)

**Comment by Ealameda31** [comment]
We can submit it to batch and await the result.

**Comment by Ealameda31** [comment]
Can we close and re-open websocket and freeze the pane?
